# Generated by Django 5.2.9 on 2025-12-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du compte')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('imap_server', models.CharField(max_length=200, verbose_name='Serveur IMAP')),
                ('imap_port', models.IntegerField(default=993, verbose_name='Port IMAP')),
                ('username', models.CharField(max_length=200, verbose_name="Nom d'utilisateur")),
                ('password', models.CharField(max_length=500, verbose_name='Mot de passe (chiffré)')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='Utiliser SSL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte Email',
                'verbose_name_plural': 'Comptes Emails',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True, verbose_name='UID IMAP')),
                ('message_id', models.CharField(max_length=500, verbose_name='Message-ID')),
                ('sender', models.EmailField(max_length=254, verbose_name='Expéditeur')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='Nom expéditeur')),
                ('recipients', models.TextField(verbose_name='Destinataires')),
                ('subject', models.TextField(verbose_name='Sujet')),
                ('received_date', models.DateTimeField(verbose_name='Date réception')),
                ('size', models.IntegerField(verbose_name='Taille (octets)')),
                ('body_text', models.TextField(blank=True, verbose_name='Corps texte')),
                ('body_html', models.TextField(blank=True, verbose_name='Corps HTML')),
                ('attachments', models.JSONField(default=list, verbose_name='Pièces jointes')),
                ('threat_level', models.CharField(choices=[('SAFE', 'Sûr'), ('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='SAFE', max_length=20, verbose_name='Niveau de menace')),
                ('threat_type', models.CharField(choices=[('PHISHING', 'Phishing'), ('SPAM', 'Spam'), ('MALWARE', 'Malware'), ('SUSPICIOUS', 'Suspect'), ('SPOOFING', 'Usurpation'), ('NONE', 'Aucune')], default='NONE', max_length=20, verbose_name='Type de menace')),
                ('risk_score', models.IntegerField(default=0, verbose_name='Score de risque')),
                ('analyzed', models.BooleanField(default=False, verbose_name='Analysé')),
                ('analysis_date', models.DateTimeField(blank=True, null=True, verbose_name='Date analyse')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='A des pièces jointes')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Chiffré')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.emailaccount')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-received_date'],
                'indexes': [models.Index(fields=['threat_level', 'received_date'], name='core_emailm_threat__1bc8e3_idx'), models.Index(fields=['sender', 'received_date'], name='core_emailm_sender_c63a60_idx')],
            },
        ),
    ]
