# Generated by Django 6.0 on 2025-12-21 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailaccount_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='is_quarantined',
            field=models.BooleanField(default=False, verbose_name='En quarantaine'),
        ),
        migrations.CreateModel(
            name='QuarantineEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254, verbose_name='Expéditeur')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='Nom expéditeur')),
                ('subject', models.TextField(verbose_name='Sujet')),
                ('received_date', models.DateTimeField(verbose_name='Date réception')),
                ('body_text', models.TextField(blank=True, verbose_name='Corps texte')),
                ('body_html', models.TextField(blank=True, verbose_name='Corps HTML')),
                ('attachments', models.JSONField(default=list, verbose_name='Pièces jointes')),
                ('threat_type', models.CharField(choices=[('PHISHING', 'Phishing'), ('SPAM', 'Spam'), ('MALWARE', 'Malware'), ('SUSPICIOUS', 'Suspect'), ('SPOOFING', 'Usurpation')], default='SUSPICIOUS', max_length=20, verbose_name='Type de menace')),
                ('risk_score', models.IntegerField(default=0, verbose_name='Score de risque')),
                ('analysis_summary', models.TextField(blank=True, verbose_name="Résumé de l'analyse")),
                ('quarantined_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de quarantaine')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('is_restored', models.BooleanField(default=False, verbose_name='Restauré')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de restauration')),
                ('reason', models.TextField(blank=True, verbose_name='Raison de la quarantaine')),
                ('size', models.IntegerField(default=0, verbose_name='Taille (octets)')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='A des pièces jointes')),
                ('original_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine', to='core.emailmessage', verbose_name='Email original')),
                ('quarantined_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mis en quarantaine par')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_quarantine', to=settings.AUTH_USER_MODEL, verbose_name='Restauré par')),
            ],
            options={
                'verbose_name': 'Email en quarantaine',
                'verbose_name_plural': 'Emails en quarantaine',
                'ordering': ['-quarantined_at'],
                'indexes': [models.Index(fields=['threat_type', 'quarantined_at'], name='core_quaran_threat__23230c_idx'), models.Index(fields=['is_restored', 'quarantined_at'], name='core_quaran_is_rest_8f6789_idx')],
            },
        ),
    ]
