# Generated by Django 6.0 on 2025-12-22 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailmessage_is_quarantined_quarantineemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('priority', models.IntegerField(default=1, verbose_name='Priorité (1=le plus haut)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Playbook',
                'verbose_name_plural': 'Playbooks',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('detected', 'Détecté'), ('quarantined', 'Mis en quarantaine'), ('deleted', 'Supprimé'), ('resolved', 'Résolu'), ('false_positive', 'Faux positif')], default='detected', max_length=50, verbose_name='Statut')),
                ('actions_executed', models.JSONField(default=list, verbose_name='Actions exécutées')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu à')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.emailmessage')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.playbook')),
            ],
            options={
                'verbose_name': "Journal d'incident",
                'verbose_name_plural': "Journaux d'incidents",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('quarantine', 'Mettre en quarantaine'), ('delete', "Supprimer l'email"), ('move_to_folder', 'Déplacer vers dossier'), ('mark_as_read', 'Marquer comme lu'), ('mark_as_unread', 'Marquer comme non lu'), ('forward', 'Transférer à'), ('reply', 'Répondre avec un modèle'), ('notify', 'Notifier par email'), ('log_only', 'Seulement journaliser'), ('create_ticket', 'Créer un ticket'), ('block_sender', "Bloquer l'expéditeur")], max_length=50, verbose_name="Type d'action")),
                ('parameters', models.JSONField(default=dict, verbose_name='Paramètres')),
                ('order', models.IntegerField(default=1, verbose_name="Ordre d'exécution")),
                ('delay_seconds', models.IntegerField(default=0, verbose_name='Délai avant exécution (secondes)')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.playbook')),
            ],
            options={
                'verbose_name': 'Action de playbook',
                'verbose_name_plural': 'Actions de playbooks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('sender', 'Expéditeur'), ('subject', 'Sujet'), ('body_text', 'Corps texte'), ('body_html', 'Corps HTML'), ('threat_level', 'Niveau de menace'), ('threat_type', 'Type de menace'), ('risk_score', 'Score de risque'), ('has_attachments', 'A des pièces jointes')], max_length=50, verbose_name='Champ')),
                ('operator', models.CharField(choices=[('contains', 'Contient'), ('equals', 'Égal à'), ('startswith', 'Commence par'), ('endswith', 'Finit par'), ('regex', 'Expression régulière'), ('gt', 'Supérieur à'), ('gte', 'Supérieur ou égal à'), ('lt', 'Inférieur à'), ('lte', 'Inférieur ou égal à')], max_length=50, verbose_name='Opérateur')),
                ('value', models.TextField(verbose_name='Valeur')),
                ('negate', models.BooleanField(default=False, verbose_name='Négation (NOT)')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.playbook')),
            ],
            options={
                'verbose_name': 'Règle de playbook',
                'verbose_name_plural': 'Règles de playbooks',
            },
        ),
    ]
