# Generated by Django 6.0 on 2025-12-22 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playbook_incidentlog_playbookaction_playbookrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playbookrule',
            options={'ordering': ['playbook', 'id'], 'verbose_name': 'Règle de playbook', 'verbose_name_plural': 'Règles de playbooks'},
        ),
        migrations.AddField(
            model_name='playbook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbooks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbook',
            name='execution_count',
            field=models.IntegerField(default=0, verbose_name="Nombre d'exécutions"),
        ),
        migrations.AddField(
            model_name='playbook',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution'),
        ),
    ]
